### PR TITLE
Add fix-win32-regex patch

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
From https://github.com/openSUSE/libsolv/pull/436

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Travis: `Job has been terminated due to insufficient credits balance` - this shouldn't stop us as the fix is for Windows only anyhow.

**Comment by Tobias-Fischer** [comment]
Other than that this is good to go @conda-forge/libsolv

**Comment by wolfv** [comment]
Thanks! Can you also add the other PR in libsolv that affects conda? It's about adding support for tar bz2 only flag when reading repodata

**Comment by Tobias-Fischer** [comment]
Done.

**Pull request merged**
